//@ui5-bundle ui5app/Component-preload.js
sap.ui.require.preload({
	"ui5app/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","ui5app/model/models"],function(e,i,t){"use strict";return e.extend("ui5app.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"ui5app/controller/App.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("ui5app.controller.App",{onInit:function(){}})});
},
	"ui5app/controller/Insurance.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/model/Filter","sap/ui/model/FilterOperator","sap/ui/core/routing/History"],function(e,n,t,o){"use strict";return e.extend("ui5app.controller.Insurance",{onInit:function(){},onFilterInsurances(e){const o=[];const i=e.getParameter("query");if(i){o.push(new n("insuranceHolder",t.Contains,i))}const r=this.byId("insuranceTable");const s=r.getBinding("items");s.filter(o)},onNavBack(){const e=o.getInstance();const n=e.getPreviousHash();if(n!==undefined){window.history.go(-1)}else{const e=this.getOwnerComponent().getRouter();e.navTo("main",{},true)}}})});
},
	"ui5app/controller/MainView.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("ui5app.controller.MainView",{onInit:function(){}})});
},
	"ui5app/controller/NewInsurance.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/routing/History"],function(n,e){"use strict";return n.extend("ui5app.controller.NewInsurance",{onInit:function(){},onNavBack(){const n=e.getInstance();const t=n.getPreviousHash();if(t!==undefined){window.history.go(-1)}else{const n=this.getOwnerComponent().getRouter();n.navTo("main",{},true)}}})});
},
	"ui5app/controller/Tiles.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller","sap/m/MessageToast"],(e,n)=>{"use strict";let s;return e.extend("ui5app.controller.Tiles",{onInit(){s=this.getOwnerComponent().getRouter()},onPressCreate(){s.navTo("newInsurance");n.show("Create New")},onPressShow(){s.navTo("insuranceList");n.show("Show")}})});
},
	"ui5app/i18n/i18n.properties":'# This is the resource bundle for ui5app\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Hansen UI5\n\n#YDES: Application description\nappDescription=ui5app description\n#XTIT: Main view title\ntitle=VKB \n\n#Home Tiles\nhome=Welcome to Insurance Manager\ncreateNewInsurance= Create Insurance\nsubtitle= Go To Create\nshowInsurances=Show All Insurances\nsubtitle2= Insurances List\n\n\n# Nav Button\ngoBackToHome= Home\n\n#Insurance List\ninsuranceNumber = Policy Number\ninsuranceHolder = Holder\ninsuranceType = Type\ndateOfCreation = Signed at\ndateOfValid = Valid until\n',
	"ui5app/manifest.json":'{"_version":"1.60.0","sap.app":{"id":"ui5app","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap-ux/fiori-freestyle-writer:basic","version":"0.21.10"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.128.1","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5app.i18n.i18n"}},"insurance":{"type":"sap.ui.model.json.JSONModel","uri":"Insurances.json"}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"ui5app.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"main","pattern":"","target":["targetMain"]},{"name":"newInsurance","pattern":"create_insurance","target":["targetNewInsurance"]},{"name":"insuranceList","pattern":"insurances","target":["targetInsuranceList"]}],"targets":{"targetMain":{"viewName":"MainView"},"targetNewInsurance":{"viewName":"NewInsurance"},"targetInsuranceList":{"viewName":"Insurance"}}},"rootView":{"viewName":"ui5app.view.App","type":"XML","async":true,"id":"app"}}}',
	"ui5app/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"ui5app/view/App.view.xml":'<mvc:View controllerName="ui5app.controller.App"\n    xmlns:html="http://www.w3.org/1999/xhtml"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns:core="sap.ui.core"\n    xmlns="sap.m"><Shell backgroundColor="#003C6C" logo="https://www.vkb.de/export/sites/vkb/_resources/bilder/vkb_logo.svg"><App id="app" class="myAppDemoWT"/></Shell></mvc:View>\n',
	"ui5app/view/Insurance.view.xml":'<mvc:View\n    controllerName="ui5app.controller.Insurance"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><Page\n\t\ttitle="{i18n>goBackToHome}"\n        showNavButton="true"\n\t\tnavButtonPress=".onNavBack"><Panel headerText="{i18n>ShowAllInsurance}"\n                class="sapUiResponsiveMargin"\n                width="auto"><content><Table id="insuranceTable" items="{insurance>/Insurances}"><headerToolbar><Toolbar><Title text="{i18n>allInsurances}"/><ToolbarSpacer/><SearchField width="50%" \n                                        search=".onFilterInsurances"/></Toolbar></headerToolbar><columns><Column><Text text="{i18n>insuranceNumber}"></Text></Column><Column><Text text="{i18n>insuranceHolder}"></Text></Column><Column><Text text="{i18n>insuranceType}"></Text></Column><Column><Text text="{i18n>dateOfCreation}"></Text></Column><Column><Text text="{i18n>dateOfValid}"></Text></Column></columns><items><ColumnListItem><cells><Text text="{insurance>insuranceNumber}"/><Text text="{insurance>insuranceHolder}"/><Text text="{insurance>insuranceType}"/><Text text="{insurance>dateOfCreation}"/><Text text="{insurance>dateOfValid}"/></cells></ColumnListItem></items></Table></content></Panel></Page></mvc:View>',
	"ui5app/view/MainView.view.xml":'<mvc:View controllerName="ui5app.controller.MainView"\n    xmlns:mvc="sap.ui.core.mvc" displayBlock="true"\n    xmlns:core="sap.ui.core"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"><headerContent><ComboBox id="combox" selectedKey="DE" selectionChange="onSelectionChange" width="55%"><items><core:Item key = "DE" text = "DE | &#x1F1E9;&#x1F1EA; "/><core:Item key = "EN" text = "EN | &#x1F1EC;&#x1F1E7;" /><core:Item key = "ID" text = "ID | &#x1F1EE;&#x1F1E9;" /><core:Item key = "CN" text = "CN | &#x1F1E8;&#x1F1F3;" /><core:Item key = "RU" text = "RU | &#x1F1F7;&#x1F1FA;" /></items></ComboBox></headerContent><content><mvc:XMLView viewName="ui5app.view.Tiles"/></content></Page></mvc:View>\n',
	"ui5app/view/NewInsurance.view.xml":'<mvc:View\n\tcontrollerName="ui5app.controller.NewInsurance"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><Page\n\t\ttitle="{i18n>goBackToHome}"\n        showNavButton="true"\n\t\tnavButtonPress=".onNavBack"><ObjectHeader title="Invoice"/></Page></mvc:View>',
	"ui5app/view/Tiles.view.xml":'<mvc:View\n   controllerName="ui5app.controller.Tiles"\n   xmlns="sap.m"\n   xmlns:mvc="sap.ui.core.mvc"><Panel\n      headerText="{i18n>home}"\n      class="sapUiResponsiveMargin"\n      width="auto"><content><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="{i18n>createNewInsurance}"\n            subheader="{i18n>subtitle}" press=".onPressCreate"><TileContent><ImageContent src="sap-icon://create-form" /></TileContent></GenericTile><GenericTile class="sapUiTinyMarginBegin sapUiTinyMarginTop tileLayout" header="{i18n>showInsurances}"\n        subheader="{i18n>subtitle2}" press=".onPressShow"><TileContent><ImageContent src="sap-icon://show" /></TileContent></GenericTile></content></Panel></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
